# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-mongo
# spec:
#   capacity:
#     storage: 10Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/volumes/mongodb"
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo-lin
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: linode-block-storage-retain